//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int job_id { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public string cv_path { get; set; }
        public System.DateTime apply_date { get; set; }
        public Nullable<int> member_id { get; set; }
        public object Job { get; internal set; }
        //public Job Job { get; set; }

    }
}
