//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyEducation
    {
        public int id { get; set; }
        public int applicant_id { get; set; }
        public string degree { get; set; }
        public string institution { get; set; }
        public string board { get; set; }
        public int total_marks { get; set; }
        public int obtained_marks { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
    }
}
