//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeRemark
    {
        public int id { get; set; }
        public int committee_member_id { get; set; }
        public int applicant_id { get; set; }
        public int job_id { get; set; }
        public int remark { get; set; }
        public System.DateTime interview_date { get; set; }
    }
}
