//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> num_of_vacancy { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string qualification { get; set; }
        public Nullable<int> salary_to { get; set; }
        public Nullable<int> salary_from { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
    }
}
